
export const GET_PROD_LOAGING = "GET_PROD_LOAGING";
export const GET_PROD_SUCCESS = "GET_PROD_SUCCESS";

export const SET_LOAGING_TRUE = "SET_LOADING_TRUE";
export const SET_LOAGING_FALSE = "SET_LOADING_FALSE";
